In [2]:
import pandas as pd

In [5]:
nhl = pd.read_csv('./NHE2020/NHE2020.csv', sep=',', encoding='latin-1')
nhl.head()

,NATIONAL HEALTH EXPENDITURES BY TYPE OF SERVICE AND SOURCE OF FUNDS: CALENDAR YEARS 1960 to 2020,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61
0,Expenditure Amount (Millions),1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,Total National Health Expenditures,"27,122","29,060","31,765","34,558","38,245","41,627","45,752","51,186","58,015",...,"2,676,178","2,782,804","2,855,822","3,001,434","3,163,647","3,305,581","3,446,492","3,604,511","3,759,123","4,124,005"
2,Out of pocket,"12,778","13,193","14,085","15,171","16,669","17,863","18,132","17,985","19,951",...,"310,012","323,020","330,632","340,298","352,917","365,609","372,568","386,536","403,683","388,646"
3,Health Insurance,"7,324","8,043","8,785","9,660","10,710","11,722","15,357","20,789","24,010",...,"1,902,166","1,971,262","2,018,651","2,150,175","2,287,588","2,395,797","2,494,482","2,613,343","2,726,359","2,809,278"
4,Private Health Insurance,"5,639","6,275","6,963","7,720","8,791","9,772","9,980","10,132","11,462",...,"850,692","877,800","878,867","921,867","975,648","1,029,776","1,079,066","1,130,967","1,165,571","1,151,356"

In [39]:
nhl = pd.read_csv('./NHE2020/NHE2020.csv', sep=',', encoding='latin-1')
nhl = nhl.drop(nhl.index[0])
text_columns = ['type']
number_columns = [
    '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969',
    '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979',
    '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989',
    '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
    '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
    '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
    '2020',
]
nhl.columns = text_columns + number_columns
nhl = nhl.fillna(0)
nhl = nhl.replace('  -    ', 0)
nhl.head()

,type,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,Total National Health Expenditures,"27,122","29,060","31,765","34,558","38,245","41,627","45,752","51,186","58,015",...,"2,676,178","2,782,804","2,855,822","3,001,434","3,163,647","3,305,581","3,446,492","3,604,511","3,759,123","4,124,005"
2,Out of pocket,"12,778","13,193","14,085","15,171","16,669","17,863","18,132","17,985","19,951",...,"310,012","323,020","330,632","340,298","352,917","365,609","372,568","386,536","403,683","388,646"
3,Health Insurance,"7,324","8,043","8,785","9,660","10,710","11,722","15,357","20,789","24,010",...,"1,902,166","1,971,262","2,018,651","2,150,175","2,287,588","2,395,797","2,494,482","2,613,343","2,726,359","2,809,278"
4,Private Health Insurance,"5,639","6,275","6,963","7,720","8,791","9,772","9,980","10,132","11,462",...,"850,692","877,800","878,867","921,867","975,648","1,029,776","1,079,066","1,130,967","1,165,571","1,151,356"
5,Medicare,0,0,0,0,0,0,"1,842","4,924","6,218",...,"544,596","568,339","588,885","617,558","647,887","675,733","704,775","749,416","801,354","829,484"

In [47]:
def number_preprocessing(item):
    item = str(item)
    if not item.isnumeric():
        item = item.replace(' ', '')
        item = item.replace(',', '')
        return float(item)
    return item

def text_preprocessing(item):
    item = str(item)
    item = item.replace('  ', ' ')
    item = item.replace('"', '')
    item = item.replace('*', '')
    item = item.strip()
    return item

for column in number_columns:
    nhl[column] = nhl[column].apply(number_preprocessing)

for column in text_columns:
    nhl[column] = nhl[column].apply(text_preprocessing)

nhl.head()

,type,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,Total National Health Expenditures,27122.0,29060.0,31765.0,34558.0,38245.0,41627.0,45752.0,51186.0,58015.0,...,2676178.0,2782804.0,2855822.0,3001434.0,3163647.0,3305581.0,3446492.0,3604511.0,3759123.0,4124005.0
2,Out of pocket,12778.0,13193.0,14085.0,15171.0,16669.0,17863.0,18132.0,17985.0,19951.0,...,310012.0,323020.0,330632.0,340298.0,352917.0,365609.0,372568.0,386536.0,403683.0,388646.0
3,Health Insurance,7324.0,8043.0,8785.0,9660.0,10710.0,11722.0,15357.0,20789.0,24010.0,...,1902166.0,1971262.0,2018651.0,2150175.0,2287588.0,2395797.0,2494482.0,2613343.0,2726359.0,2809278.0
4,Private Health Insurance,5639.0,6275.0,6963.0,7720.0,8791.0,9772.0,9980.0,10132.0,11462.0,...,850692.0,877800.0,878867.0,921867.0,975648.0,1029776.0,1079066.0,1130967.0,1165571.0,1151356.0
5,Medicare,0,0,0,0,0,0,1842.0,4924.0,6218.0,...,544596.0,568339.0,588885.0,617558.0,647887.0,675733.0,704775.0,749416.0,801354.0,829484.0

In [48]:
nhl.to_csv('./NHE2020/NHE2020_preprocessed.csv', index=False)